// <auto-generated />
namespace DataAccessLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class mig4_image_size_change : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mig4_image_size_change));
        
        string IMigrationMetadata.Id
        {
            get { return "202504191008218_mig4_image_size_change"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
